# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'Healer' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Healer
pod 'MJExtension', '~> 3.0.13'
  target 'HealerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
